/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppYieldRouteImport } from './routes/_app.yield'
import { Route as AppRootCauseRouteImport } from './routes/_app.root-cause'
import { Route as AppPredictiveMaintenanceRouteImport } from './routes/_app.predictive-maintenance'
import { Route as AppMonitoringRouteImport } from './routes/_app.monitoring'
import { Route as AppModelPerformanceRouteImport } from './routes/_app.model-performance'
import { Route as AppFaultDetectionRouteImport } from './routes/_app.fault-detection'
import { Route as AppFabMapRouteImport } from './routes/_app.fab-map'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppYieldRoute = AppYieldRouteImport.update({
  id: '/yield',
  path: '/yield',
  getParentRoute: () => AppRoute,
} as any)
const AppRootCauseRoute = AppRootCauseRouteImport.update({
  id: '/root-cause',
  path: '/root-cause',
  getParentRoute: () => AppRoute,
} as any)
const AppPredictiveMaintenanceRoute =
  AppPredictiveMaintenanceRouteImport.update({
    id: '/predictive-maintenance',
    path: '/predictive-maintenance',
    getParentRoute: () => AppRoute,
  } as any)
const AppMonitoringRoute = AppMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AppRoute,
} as any)
const AppModelPerformanceRoute = AppModelPerformanceRouteImport.update({
  id: '/model-performance',
  path: '/model-performance',
  getParentRoute: () => AppRoute,
} as any)
const AppFaultDetectionRoute = AppFaultDetectionRouteImport.update({
  id: '/fault-detection',
  path: '/fault-detection',
  getParentRoute: () => AppRoute,
} as any)
const AppFabMapRoute = AppFabMapRouteImport.update({
  id: '/fab-map',
  path: '/fab-map',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/fab-map': typeof AppFabMapRoute
  '/fault-detection': typeof AppFaultDetectionRoute
  '/model-performance': typeof AppModelPerformanceRoute
  '/monitoring': typeof AppMonitoringRoute
  '/predictive-maintenance': typeof AppPredictiveMaintenanceRoute
  '/root-cause': typeof AppRootCauseRoute
  '/yield': typeof AppYieldRoute
}
export interface FileRoutesByTo {
  '/fab-map': typeof AppFabMapRoute
  '/fault-detection': typeof AppFaultDetectionRoute
  '/model-performance': typeof AppModelPerformanceRoute
  '/monitoring': typeof AppMonitoringRoute
  '/predictive-maintenance': typeof AppPredictiveMaintenanceRoute
  '/root-cause': typeof AppRootCauseRoute
  '/yield': typeof AppYieldRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/fab-map': typeof AppFabMapRoute
  '/_app/fault-detection': typeof AppFaultDetectionRoute
  '/_app/model-performance': typeof AppModelPerformanceRoute
  '/_app/monitoring': typeof AppMonitoringRoute
  '/_app/predictive-maintenance': typeof AppPredictiveMaintenanceRoute
  '/_app/root-cause': typeof AppRootCauseRoute
  '/_app/yield': typeof AppYieldRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fab-map'
    | '/fault-detection'
    | '/model-performance'
    | '/monitoring'
    | '/predictive-maintenance'
    | '/root-cause'
    | '/yield'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/fab-map'
    | '/fault-detection'
    | '/model-performance'
    | '/monitoring'
    | '/predictive-maintenance'
    | '/root-cause'
    | '/yield'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/fab-map'
    | '/_app/fault-detection'
    | '/_app/model-performance'
    | '/_app/monitoring'
    | '/_app/predictive-maintenance'
    | '/_app/root-cause'
    | '/_app/yield'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/yield': {
      id: '/_app/yield'
      path: '/yield'
      fullPath: '/yield'
      preLoaderRoute: typeof AppYieldRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/root-cause': {
      id: '/_app/root-cause'
      path: '/root-cause'
      fullPath: '/root-cause'
      preLoaderRoute: typeof AppRootCauseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/predictive-maintenance': {
      id: '/_app/predictive-maintenance'
      path: '/predictive-maintenance'
      fullPath: '/predictive-maintenance'
      preLoaderRoute: typeof AppPredictiveMaintenanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitoring': {
      id: '/_app/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AppMonitoringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/model-performance': {
      id: '/_app/model-performance'
      path: '/model-performance'
      fullPath: '/model-performance'
      preLoaderRoute: typeof AppModelPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fault-detection': {
      id: '/_app/fault-detection'
      path: '/fault-detection'
      fullPath: '/fault-detection'
      preLoaderRoute: typeof AppFaultDetectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fab-map': {
      id: '/_app/fab-map'
      path: '/fab-map'
      fullPath: '/fab-map'
      preLoaderRoute: typeof AppFabMapRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppFabMapRoute: typeof AppFabMapRoute
  AppFaultDetectionRoute: typeof AppFaultDetectionRoute
  AppModelPerformanceRoute: typeof AppModelPerformanceRoute
  AppMonitoringRoute: typeof AppMonitoringRoute
  AppPredictiveMaintenanceRoute: typeof AppPredictiveMaintenanceRoute
  AppRootCauseRoute: typeof AppRootCauseRoute
  AppYieldRoute: typeof AppYieldRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFabMapRoute: AppFabMapRoute,
  AppFaultDetectionRoute: AppFaultDetectionRoute,
  AppModelPerformanceRoute: AppModelPerformanceRoute,
  AppMonitoringRoute: AppMonitoringRoute,
  AppPredictiveMaintenanceRoute: AppPredictiveMaintenanceRoute,
  AppRootCauseRoute: AppRootCauseRoute,
  AppYieldRoute: AppYieldRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
